repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: make-build
        name: make build
        entry: make build
        language: system
        pass_filenames: false
